### ISSUE TITLE
undefined is not a constructor

### ISSUE THREAD

**Issue by skywarspro15** [datkat21/Pluto-TS-DevEnv#1]
#  Issue

I wanted to try out Pluto's new TypeScript development environment as I want to make apps with type safety as well as easier bundling. I followed the instructions in the README, as well as install its' dependencies. It ran successfully the first time, but when trying to run Pluview, or try to access the app listing, it spat out this error message: 

```
 6 | export default function serve() {
 7 |   const app = express();
 8 |   app.use(cors());
 9 | 
10 |   app.get('/apps', async (req, res) => {
11 |     const glob = new Glob("*.js");
                     ^
TypeError: undefined is not a constructor (evaluating 'new Glob("*.js")')
      at /root/Pluto-TS-DevEnv/serve.ts:11:17
      at /root/Pluto-TS-DevEnv/serve.ts:10:26
```

# Current Setup

I'm running on Windows 10, with WSL (Ubuntu) for full Bun support. It's currently running at version `1.0.0`. 

# Steps to Replicate

1. Run the dev server using `bun start`. 
2. Go to your Pluto instance and open Pluview, or open the dev server's address and open its' app listing. 
3. The app will hang, and an error is logged to the terminal. 

Here's a video to demonstrate:

https://github.com/datkat21/Pluto-TS-DevEnv/assets/86519653/5551356b-af77-4a7e-a9b1-998ae7e664b7

# Full Stack Trace

```
 6 | export default function serve() {
 7 |   const app = express();
 8 |   app.use(cors());
 9 | 
10 |   app.get('/apps', async (req, res) => {
11 |     const glob = new Glob("*.js");
                     ^
TypeError: undefined is not a constructor (evaluating 'new Glob("*.js")')
      at /root/Pluto-TS-DevEnv/serve.ts:11:17
      at /root/Pluto-TS-DevEnv/serve.ts:10:26
      at handle (/root/Pluto-TS-DevEnv/node_modules/express/lib/router/layer.js:95:4)
      at next (/root/Pluto-TS-DevEnv/node_modules/express/lib/router/route.js:144:6)
      at dispatch (/root/Pluto-TS-DevEnv/node_modules/express/lib/router/route.js:114:2)
      at handle (/root/Pluto-TS-DevEnv/node_modules/express/lib/router/layer.js:95:4)
      at /root/Pluto-TS-DevEnv/node_modules/express/lib/router/index.js:284:8
      at process_params (/root/Pluto-TS-DevEnv/node_modules/express/lib/router/index.js:346:11)
      at next (/root/Pluto-TS-DevEnv/node_modules/express/lib/router/index.js:280:4)
      at cors (/root/Pluto-TS-DevEnv/node_modules/cors/lib/index.js:188:6)
      at /root/Pluto-TS-DevEnv/node_modules/cors/lib/index.js:224:16
      at originCallback (/root/Pluto-TS-DevEnv/node_modules/cors/lib/index.js:214:14)
      at /root/Pluto-TS-DevEnv/node_modules/cors/lib/index.js:219:12
      at optionsCallback (/root/Pluto-TS-DevEnv/node_modules/cors/lib/index.js:199:8)
      at corsMiddleware (/root/Pluto-TS-DevEnv/node_modules/cors/lib/index.js:204:6)
      at handle (/root/Pluto-TS-DevEnv/node_modules/express/lib/router/layer.js:95:4)
      at trim_prefix (/root/Pluto-TS-DevEnv/node_modules/express/lib/router/index.js:328:6)
      at /root/Pluto-TS-DevEnv/node_modules/express/lib/router/index.js:286:8
      at process_params (/root/Pluto-TS-DevEnv/node_modules/express/lib/router/index.js:346:11)
      at next (/root/Pluto-TS-DevEnv/node_modules/express/lib/router/index.js:280:4)
      at expressInit (/root/Pluto-TS-DevEnv/node_modules/express/lib/middleware/init.js:40:4)
      at handle (/root/Pluto-TS-DevEnv/node_modules/express/lib/router/layer.js:95:4)
      at trim_prefix (/root/Pluto-TS-DevEnv/node_modules/express/lib/router/index.js:328:6)
      at /root/Pluto-TS-DevEnv/node_modules/express/lib/router/index.js:286:8
      at process_params (/root/Pluto-TS-DevEnv/node_modules/express/lib/router/index.js:346:11)
      at next (/root/Pluto-TS-DevEnv/node_modules/express/lib/router/index.js:280:4)
      at query (/root/Pluto-TS-DevEnv/node_modules/express/lib/middleware/query.js:45:4)
      at handle (/root/Pluto-TS-DevEnv/node_modules/express/lib/router/layer.js:95:4)
      at trim_prefix (/root/Pluto-TS-DevEnv/node_modules/express/lib/router/index.js:328:6)
      at /root/Pluto-TS-DevEnv/node_modules/express/lib/router/index.js:286:8
      at process_params (/root/Pluto-TS-DevEnv/node_modules/express/lib/router/index.js:346:11)
      at next (/root/Pluto-TS-DevEnv/node_modules/express/lib/router/index.js:280:4)
```

**Comment by datkat21** [comment]
I'm running with Bun `v1.0.20`, maybe Glob wasn't a constructor in 1.0.0. I'll try to repro this on my machine

**Comment by datkat21** [comment]
A fresh clone of the repo works with v1.0.20 on my machine. I'll test on v1.0.0 soon (if i can, that is)

**Comment by datkat21** [comment]
Please try with the latest version of Bun here: [https://bun.sh/blog/bun-v1.0.25](https://bun.sh/blog/bun-v1.0.25)

**Comment by datkat21** [comment]
I would also recommend to pull as I just made some changes to types and improved some of the getting started instructions so it is more clear.
